[package]
name = "polarsteps-to-gpx"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
geo-types = { version = "0.7", default-features = false }
gpx = "0.10"
serde_json = "1"
time = { version = "0.3", default-features = false }
